export const RESERVATION_ERROR = {
  VALIDATION_FAILED: "RESERVATION_VALIDATION_FAILED",
  RESTAURANT_NOT_FOUND: "RESERVATION_RESTAURANT_NOT_FOUND",
  CLOSED_DAY: "RESERVATION_CLOSED_DAY",
  OUTSIDE_HOURS: "RESERVATION_OUTSIDE_HOURS",
  EXCEEDS_CLOSING: "RESERVATION_EXCEEDS_CLOSING",
  ADVANCE_NOTICE_REQUIRED: "RESERVATION_ADVANCE_NOTICE_REQUIRED",
  PAST_TIME_NOT_ALLOWED: "RESERVATION_PAST_TIME_NOT_ALLOWED",
  FULLY_BOOKED: "RESERVATION_FULLY_BOOKED",
  NOT_FOUND: "RESERVATION_NOT_FOUND",
  INVALID_CANCEL_TOKEN: "RESERVATION_INVALID_CANCEL_TOKEN",
  ALREADY_CANCELLED: "RESERVATION_ALREADY_CANCELLED",
  CANNOT_CANCEL_COMPLETED: "RESERVATION_CANNOT_CANCEL_COMPLETED",
  CANNOT_CANCEL_NOSHOW: "RESERVATION_CANNOT_CANCEL_NOSHOW",
  CANNOT_CANCEL: "RESERVATION_CANNOT_CANCEL",
  CUTOFF_EXCEEDED: "RESERVATION_CUTOFF_EXCEEDED",
  INVALID_STATUS_TRANSITION: "RESERVATION_INVALID_STATUS_TRANSITION",
  EARLY_NO_SHOW: "RESERVATION_EARLY_NO_SHOW",
  DEMO_RESTRICTED: "RESERVATION_DEMO_RESTRICTED",
  SERVER_ERROR: "RESERVATION_SERVER_ERROR",
} as const;

export type ReservationErrorCode = (typeof RESERVATION_ERROR)[keyof typeof RESERVATION_ERROR];

export const TABLE_ERROR = {
  VALIDATION_FAILED: "TABLE_VALIDATION_FAILED",
  RESTAURANT_NOT_FOUND: "TABLE_RESTAURANT_NOT_FOUND",
  HAS_FUTURE_RESERVATIONS: "TABLE_HAS_FUTURE_RESERVATIONS",
  CAPACITY_CONFLICT: "TABLE_CAPACITY_CONFLICT",
  DEMO_RESTRICTED: "TABLE_DEMO_RESTRICTED",
  SERVER_ERROR: "TABLE_SERVER_ERROR",
} as const;

export type TableErrorCode = (typeof TABLE_ERROR)[keyof typeof TABLE_ERROR];

export const AUTH_ERROR = {
  UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  FORBIDDEN: "AUTH_FORBIDDEN",
  DEMO_RESTRICTED: "AUTH_DEMO_RESTRICTED",
  VALIDATION_FAILED: "AUTH_VALIDATION_FAILED",
  USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  CANNOT_DELETE_SELF: "AUTH_CANNOT_DELETE_SELF",
  CANNOT_DEMOTE_LAST_MANAGER: "AUTH_CANNOT_DEMOTE_LAST_MANAGER",
  CANNOT_DELETE_LAST_MANAGER: "AUTH_CANNOT_DELETE_LAST_MANAGER",
  CANNOT_MODIFY_DEMO: "AUTH_CANNOT_MODIFY_DEMO",
  PASSWORD_CHANGE_FAILED: "AUTH_PASSWORD_CHANGE_FAILED",
  SERVER_ERROR: "AUTH_SERVER_ERROR",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR)[keyof typeof AUTH_ERROR];

export const CMS_ERROR = {
  VALIDATION_FAILED: "CMS_VALIDATION_FAILED",
  FORBIDDEN: "CMS_FORBIDDEN",
  SERVER_ERROR: "CMS_SERVER_ERROR",
} as const;

export type CmsErrorCode = (typeof CMS_ERROR)[keyof typeof CMS_ERROR];
